// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-BLw5azKvDGRBr36pYsYCOClx8XxNZ-4',
    appId: '1:636955805916:android:6c29a79823499593e48c19',
    messagingSenderId: '636955805916',
    projectId: 'project-f8940',
    storageBucket: 'project-f8940.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt-IPuftFMiRwkwmWB2voHqM_R8rygSBU',
    appId: '1:636955805916:ios:fbccd12ed66430abe48c19',
    messagingSenderId: '636955805916',
    projectId: 'project-f8940',
    storageBucket: 'project-f8940.appspot.com',
    iosBundleId: 'com.example.companionApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWys3rEwuIcdpVHEa72oct1BzhldA0m4A',
    appId: '1:636955805916:web:7c69446abb71adbee48c19',
    messagingSenderId: '636955805916',
    projectId: 'project-f8940',
    authDomain: 'project-f8940.firebaseapp.com',
    storageBucket: 'project-f8940.appspot.com',
    measurementId: 'G-NM87TR015Q',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWys3rEwuIcdpVHEa72oct1BzhldA0m4A',
    appId: '1:636955805916:web:ab79a5fa81aa7f63e48c19',
    messagingSenderId: '636955805916',
    projectId: 'project-f8940',
    authDomain: 'project-f8940.firebaseapp.com',
    storageBucket: 'project-f8940.appspot.com',
    measurementId: 'G-1SHWE0NN3M',
  );

}